---
- name: napalm 
  hosts: tor
  gather_facts: False
  tasks:
    - name: Retrieve get_facts, get_interfaces
      napalm_get_facts:
        filter: facts,interfaces
        dev_os: nxos_ssh
        # Specify NX-API Port
        #optional_args:
          #port: 443

    - debug:
        var: napalm_facts
