---
  ##Generate Config 
  - name: Template Configuration
    template: src={{item.src}} dest={{item.dest}}
    with_items:
      - { src: '../templates/full.j2' , dest: 'napalmconfig/{{ inventory_hostname }}.full' }
