---
  - name: Full nxos_ssh Configuration
    napalm_install_config:
      hostname: "{{ inventory_hostname }}"
      username: "{{ ansible_user }}"
      password: "{{ ansible_password }}"
      dev_os: "{{ dev_os }}"
      config_file: '../../../napalmconfig/{{ inventory_hostname }}.full'
      commit_changes: "{{ commit_action }}"
      replace_config: True
      timeout: 300
      diff_file: '../../../napalmdiff/{{ inventory_hostname }}.full.diff'
